---
  hosts: localhost
  tasks:
  - name: copy main.js from S3 bucket
    shell: aws s3 cp s3://ramgaddebucket2/main.js .


  hosts: webservers
  remote_user: ec2-user
  tasks:
  - name: Reboot the prod webserver
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30

  - name: Move main.js to webserver
    copy:
      src: main.js
      dest: /main.js
      owner: ec2-user
      group: ec2-user
      mode: '0644'
      follow: no
  - name: start the web applicaion
    shell: nohup node /main.js &