---
- hosts: localhost
  become: true
  tasks:
    - name: copy main.js from S3 bucket
      shell: aws s3 cp s3://ramgaddebucket2/main.js .


- hosts: webservers
  become: true
  remote_user: ec2-user
  tasks:
    - name: Move main.js to webserver
      copy:
        src: main.js
        dest: /main.js
        owner: ec2-user
        group: ec2-user
        mode: '0644'
        follow: no
    - name: reboot the server
      shell: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
      async: 1
      poll: 0
      become: true


