---
- hosts: webservers
  become: true
  remote_user: ec2-user
  tasks:
    - name: setup nodejs repo
      shell: curl --silent --location https://rpm.nodesource.com/setup_12.x | bash -

    - name: yum clean all
      shell: yum clean all
      ignore_errors: yes
    
    - name: Install node.js
      yum:	      
        name: nodejs
        state: latest

    - name: Check whether rc.local contains server start up command
      command: grep node /etc/rc.local
      register: checkmyconf
      ignore_errors: yes

    - name: Add node if it does not exist
      shell: node /main.js & >> /etc/rc.local
      when: checkmyconf.rc == 1

    - name: Changing perm of /etc/rc.d/rc.local, adding "+x"
      file: dest=/etc/rc.d/rc.local mode=a+x

    - name: Move main.js to webserver
      copy:
        src: main.js
        dest: /main.js
        owner: ec2-user
        group: ec2-user
        mode: '0644'
        follow: no
  
    - name: reboot the server
      shell: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
      async: 1
      poll: 0
      become: true


